// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ong-landing/Enraizada.tsx": () => import("../components/mockups/ong-landing/Enraizada.tsx"),
  "./components/mockups/ong-landing/Girassol.tsx": () => import("../components/mockups/ong-landing/Girassol.tsx")
};
